package com.revimedia.testing.cds.constants;

/**
 * Created by dstoianov on 5/5/2014, 5:42 PM.
 */
public class Disclaimers {

    // all data for http://docs.stagingrevi.com/Bq.Config.js.html

    public static final String PP_TU = " <a href=\"http://www.bestquotes.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> -\n" + " <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms of Use</a>\n";
    public static final String PP_TC = "<a target=\"_blank\" href=\"http://www.bestquotes.com/privacy-policy/\">Privacy Policy</a> - <a target=\"_blank\" href=\"http://www.bestquotes.com/terms-and-conditions/\">Terms and Conditions</a>";
    public static final String PP_TC_HOMESECUTITY = "<span> HomeSafety.com Copyright © 2014. All rights reserved. <a class=\"hs-pp-footer\" href=\"http://www.homesafety.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> - <a href=\"http://www.homesafety.com/terms-and-conditions/\" target=\"_blank\">Terms of Use</a></span>";
    public static final String PP_TC_HOMESECUTITY_M = "<a target=\"_blank\" href=\"http://www.homesafety.com/privacy-policy\">Privacy Policy</a> - <a target=\"_blank\" href=\"http://www.homesafety.com/terms-and-conditions/\">Terms and Conditions</a>";
    public static final String PP_TC_HOMESECUTITY_POP_UNDER = "<a href=\"http://www.homesafety.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> - <a href=\"http://www.homesafety.com/terms-and-conditions/\" target=\"_blank\">Terms of Use</a>";
    public static final String DISCLAIMER_AUTO = "By submitting my information I agree to the <a href=\"http://www.bestquotes.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> and <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms and Conditions</a> of this website and agree to be bound by them. I acknowledge that I am seeking a quote request, which I authorize and agree that up to eight insurance companies, their agents and partner companies may use the information I provided to contact me or to obtain additional information. I authorize this website, insurance companies or their agents that receive my insurance quote request from this website, or its partner companies, to confirm my information through the use of a consumer report, including my driving record. None of the listed companies sponsor, endorse or are in any way affiliated to this website.";
    public static final String DISCLAIMER_HEALTHSECURITY = "<div class=\"bq-footnote-discl\"><span class=\"bq-footnote\">1</span> http://www.prnewswire.com/news-releases/survey-finds-insurance-carriers-offer-major-discounts-for-home-alarm-systems-116654399.html</div>By submitting my information I agree to the <a href=\"https://www.homesafety.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> and <a href=\"https://www.homesafety.com/terms-and-conditions/\" target=\"_blank\">Terms and Conditions</a> of this website and agree to be bound by them. I acknowledge that I am seeking a quote request, which I authorize and agree that up to four security companies, their dealers and partner companies may use the information I provided to contact me or to obtain additional information. None of the listed companies sponsor, endorse or are in any way affiliated to this website.";
    //    public static final String DISCLAIMER_HEALTH = "By submitting my information I agree to the <a href=\"http://www.bestquotes.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> and <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms and Conditions</a> of this website and agree to be bound by them. I acknowledge that I am seeking a quote request, which I authorize and agree that up to eight insurance companies, their agents and partner companies may use the information I provided to contact me or to obtain additional information. I authorize this website, insurance companies or their agents that receive my insurance quote request from this website, or its partner companies, to confirm my information through the use of a consumer report. None of the listed companies sponsor, endorse or are in any way affiliated to this website.<br><br>*** Matched companies included but not limited to: Aetna, AHCP, AIG, Allied Insurance, All Web Leads, American Continental, American Family, American Republic, Anthem/BCBS, Assurant, Bankers Life and Casualty, Bankrate, BlueCross/Blue Sheild Association Companies, Cigna, Coventry, Fortis, Genworth Financial, Gerber, Golden Rule, GHI, Health Net, HealthMarkets/Insphere, HealthPlanOne, Highmark, Home Bundles, HPO, Humana, Inside Response, Insphere, Kaiser, Medicare Solutions, Mutual of Omaha, Precise Leads, Quotewizard, ReviMedia, Secure Horizons, SelectQuote, Sterling, United Healthcare, Universal American, United Medicare, WellPoint.";
    public static final String DISCLAIMER_HOME = "By submitting my information I agree to the <a href=\"http://www.bestquotes.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> and <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms and Conditions</a> of this website and agree to be bound by them. I acknowledge that I am seeking a quote request, which I authorize and agree that up to eight insurance companies, their agents and partner companies may use the information I provided to contact me or to obtain additional information. I authorize this website, insurance companies or their agents that receive my insurance quote request from this website, or its partner companies, to confirm my information through the use of a consumer report. None of the listed companies sponsor, endorse or are in any way affiliated to this website.";
    public static final String DISCLAIMER_HEALTH = "By submitting my information I agree to the <a href=\"http://www.bestquotes.com/privacy-policy/\" target=\"_blank\">Privacy Policy</a> and <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms and Conditions</a> of this website and agree to be bound by them. I acknowledge that I am seeking a quote request, which I authorize and agree that up to eight insurance companies, their agents and partner companies may use the information I provided to contact me or to obtain additional information. I authorize this website, insurance companies or their agents that receive my insurance quote request from this website, or its partner companies, to confirm my information through the use of a consumer report. None of the listed companies sponsor, endorse or are in any way affiliated to this website. <br>By completing the contact form above or calling the number listed above, you will be directed to a licensed sales agent who can answer your questions and provide information about Medicare Advantage, Part D or Medicare supplement insurance plans. Agents are not connected with or endorsed by the U.S. government or the federal Medicare program.";
    public static final String PP_HEALTH_A = "<a href=\"http://www.bestquotes.com/privacy-policy\" target=\"_blank\">Privacy Policy</a> - <a href=\"http://www.bestquotes.com/terms-and-conditions/\" target=\"_blank\">Terms of Use</a>";

    public static final String HP = "<a href=\"https://www.homesafety.com/\" target=\"_blank\">Home Page</a>";
    //    public static final String TCPA_DISCLAIMER_AUTO = "<label><input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By submitting this form, I authorize <a href=\"http://www.bestquotes.com/auto/auto-companies.html\" target=\"_blank\"> insurance companies, their agents and partners </a> to contact me by phone calls and text messages to the number I provided. I agree to receive telemarketing calls and pre-recorded messages via an autodialed phone system. I understand that my consent is not a condition of purchase.</label>";
    public static final String TCPA_DISCLAIMER_AUTO = "<label><input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By submitting this form, I authorize <a href=\"http://www.bestquotes.com/auto/auto-companies.html\" target=\"_blank\"> insurance companies, their agents and partners </a> to contact me by phone calls and text messages to the number I provided. I agree to receive telemarketing calls and pre-recorded messages via an automatic telephone dialing system. I understand that my consent is not a condition of purchase.</label>";
    public static final String TCPA_DISCLAIMER_HEALTH = "<label><input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By submitting this form, I authorize <a href=\"http://www.bestquotes.com/health/health-companies.html\" target=\"_blank\">insurance companies, their agents and partners</a> to contact me by phone calls and text messages to the number I provided. I agree to receive telemarketing calls and pre-recorded messages via an autodialed phone system. I understand that my consent is not a condition of purchase.</label>";
    public static final String TCPA_DISCLAIMER_HOME = "<label><input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By submitting this form, I authorize <a href=\"http://www.bestquotes.com/home/home-companies.html\" target=\"_blank\">insurance companies, their agents and partners</a> to contact me by phone calls and text messages to the number I provided. I agree to receive telemarketing calls and pre-recorded messages via an autodialed phone system. I understand that my consent is not a condition of purchase.</label>";
    public static final String TCPA_DISCLAIMER_SECURITY = "<label> <input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By submitting this form and requesting quotes, I authorize that <a href=\"http://www.bestquotes.com/home-security/home-security-companies.html\" target=\"_blank\">security companies, their dealers and partner companies</a> as listed below*** may contact me via telephone, including calls and/or text messages to the phone number I provided above. I authorize that these marketing communications may be delivered to me using an automatic telephone dialing system or by pre-recorded message. I understand that consent is not a condition of purchase. </label>";
    public static final String TCPA_DISCLAIMER_HOMESECURITY = "<label><input type=\"hidden\" id=\"leadid_tcpa_disclosure\">By clicking Get My Quotes, I authorize <a href=\"https://www.homesafety.com/home-security/home-security-companies.html\" target=\"_blank\">security companies</a>, including ADT, Alliance, FrontPoint, Gaylord, LifeShield, Monitronics, Protect America, Protect Your Home – ADT Authorized Premier Provider, Protection1, Vivint, their dealers and partner companies to contact me by phone calls and text messages to the number I provided. I authorize that these marketing communications may be delivered to me using an automatic telephone dialing system or by prerecorded message. I understand that my consent is not a condition of purchase.</label>";

    public static final String PRIVACY_POLICY = "Privacy Policy";
    public static final String TERM_OF_USE = "Terms of Use";
    public static final String TERM_AND_CONDITIONS = "Terms and Conditions";
    public static final String INSURANCE_COMPANIES_AUTO = "insurance companies, their agents and partners";
    public static final String INSURANCE_COMPANIES = "insurance companies, their agents and partners";
    public static final String SECURITY_COMPANIES = "security companies";
    public static final String HOME_PAGE = "Home Page";

}
